apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argo-cd
spec:
  destination:
    name: TestCluster
    namespace: argo-cd
  project: testcluster
  source:
    chart: frontend
    helm:
      values: |-
        ingress:
          enabled: true
          hostname: phpmyadmin.devk8s.vibrenthealth.com
    repoURL: demo.goharbor.io/openinnovationai
    targetRevision: 0.1.0