apiVersion: v1
data:
  ForceHttpBasicAuth: dHJ1ZQ==
  enableOCI: dHJ1ZQ==
  name: aGFyYm9y
  password: VGFubWF5QDg4OTgK
  type: aGVsbQ==
  url: ZGVtby5nb2hhcmJvci5pby9vcGVuaW5ub3ZhdGlvbmFp
  username: dGFubWF5ODg5OA==
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: vibrent-repo-secret
  namespace: argo-cd
