apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testcluster
  namespace: argo-cd
spec:
  description: Project created for managing all application in eks cluster
  destinations:
  - name: TestProject
    namespace: '*'
    server: https://6FB0823BD96D3AA787CC634FE9D3CF29.gr7.ap-south-1.eks.amazonaws.com
  sourceRepos:
  - '*'